### ISSUE TITLE
Indentation error 

### ISSUE THREAD

**Issue by SilverAB2** [mavhc/shrink-video-recursive-python#1]
Am getting this error when running the code can u help me?

**Comment by mavhc** [comment]
What line does it say it's happening on?

**Comment by SilverAB2** [comment]
> What line does it say it's happening on?

It says 
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 2
    ​# Python 3.4 program to recursively scan from current folder
IndentationError: unexpected indent
